// Abbreviations glossary (445 entries) for Explore ▸ Abbreviations.
// Grouped A–Z. Fields: a (abbreviation), full (name), note (optional), smiles (optional).
(function () {
  window.NR_ABBREV = [
    { group: "A", items: [
      { a: "AA", full: "asymmetric aminohydroxylation", note: "", smiles: "" },
      { a: "Ac", full: "acetyl", note: "Ester protecting group", smiles: "*C(C)=O" },
      { a: "acac", full: "acetylacetonyl", note: "", smiles: "CC(=O)CC(C)=O" },
      { a: "acaen", full: "N,N'-bis(1-methyl-3-oxobutylidene)ethylenediamine", note: "", smiles: "" },
      { a: "AD", full: "asymmetric dihydroxylation", note: "", smiles: "" },
      { a: "ad", full: "adamantyl", note: "", smiles: "*C1(CC2CC3C1)CC(C2)C3" },
      { a: "ADDP", full: "1,1'-(azodicarbonyl)dipiperidine", note: "", smiles: "O=C(N1CCCCC1)N=NC(=O)N1CCCCC1" },
      { a: "ADMET", full: "acyclic diene metathesis polymerization", note: "", smiles: "" },
      { a: "AIBN", full: "2,2'-azo bisisobutyronitrile", note: "Radical initiator", smiles: "N#CC(C)(C)N=NC(C)(C)C#N" },
      { a: "Alloc", full: "allyloxycarbonyl", note: "", smiles: "*C(=O)OCC=C" },
      { a: "Am", full: "amyl (n-pentyl)", note: "", smiles: "*CCCCC" },
      { a: "An", full: "p-anisyl", note: "", smiles: "*c1ccc(OC)cc1" },
      { a: "ANRORC", full: "anionic ring-opening ring-closing", note: "", smiles: "" },
      { a: "aq", full: "aqueous", note: "", smiles: "" },
      { a: "AQN", full: "anthraquinone", note: "", smiles: "O=C1c2ccccc2C(=O)c2ccccc12" },
      { a: "Ar", full: "aryl (substituted aromatic ring)", note: "", smiles: "" },
      { a: "ATD", full: "aluminum tris(2,6-di-tert-butyl-4-methylphenoxide)", note: "", smiles: "" },
      { a: "atm", full: "1 atmosphere = 10^5 Pa (pressure)", note: "", smiles: "" },
      { a: "ATPH", full: "aluminum tris(2,6-diphenylphenoxide)", note: "", smiles: "" },
    ] },
    { group: "B", items: [
      { a: "BBN (9-BBN)", full: "9-borabicyclo[3.3.1]nonane", note: "Regioselective hydroboration reagent", smiles: "" },
      { a: "BCME", full: "bis(chloromethyl)ether", note: "", smiles: "ClCOCCl" },
      { a: "BCN", full: "N-benzyloxycarbonyloxy-5-norbornene-2,3-dicarboximide", note: "", smiles: "" },
      { a: "BDPP", full: "(2R,4R) or (2S,4S) bis(diphenylphosphino)pentane", note: "", smiles: "" },
      { a: "BER", full: "borohydride exchange resin", note: "", smiles: "" },
      { a: "BHT", full: "2,6-di-t-butyl-p-cresol (butylated hydroxytoluene)", note: "", smiles: "Cc1cc(C(C)(C)C)c(O)c(C(C)(C)C)c1" },
      { a: "BICP", full: "2(R)-2'(R)-bis(diphenylphosphino)-1(R),1'(R)-dicyclopentane", note: "", smiles: "" },
      { a: "BINAL-H", full: "2,2'-dihydroxy-1,1'-binaphthyl lithium aluminum hydride", note: "", smiles: "" },
      { a: "BINAP", full: "2,2'-bis(diphenylphosphino)-1,1'-binaphthyl", note: "Chiral bidentate ligand", smiles: "" },
      { a: "BINOL", full: "1,1'-bi-2,2'-naphthol", note: "", smiles: "Oc1ccc2ccccc2c1-c1c(O)ccc2ccccc12" },
      { a: "Bip", full: "biphenyl-4-sulfonyl", note: "", smiles: "" },
      { a: "bipy", full: "2,2'-bipyridyl", note: "", smiles: "c1ccc(-c2ccccn2)nc1" },
      { a: "BLA", full: "Bronsted acid assisted chiral Lewis acid", note: "", smiles: "" },
      { a: "bmin", full: "1-butyl-3-methylimidazolium cation", note: "", smiles: "" },
      { a: "BMS", full: "borane-dimethyl sulfide complex", note: "", smiles: "B.CSC" },
      { a: "Bn", full: "benzyl", note: "Alcohol/amine PG, hydrogenolysis", smiles: "*Cc1ccccc1" },
      { a: "BNAH", full: "1-benzyl-1,4-dihydronicotinamide", note: "", smiles: "" },
      { a: "BOB", full: "4-benzyloxybutyryl", note: "", smiles: "" },
      { a: "Boc", full: "t-butoxycarbonyl", note: "Acid-labile amine PG", smiles: "*C(=O)OC(C)(C)C" },
      { a: "BOM", full: "benzyloxymethyl", note: "", smiles: "*COCc1ccccc1" },
      { a: "BOP-Cl", full: "bis(2-oxo-3-oxazolidinyl)phosphinic chloride", note: "", smiles: "" },
      { a: "bp", full: "boiling point", note: "", smiles: "" },
      { a: "BPD", full: "bis(pinacolato)diboron", note: "", smiles: "CC1(C)OB(OC1(C)C)B1OC(C)(C)C(C)(C)O1" },
      { a: "BPO", full: "benzoyl peroxide", note: "", smiles: "O=C(OOC(=O)c1ccccc1)c1ccccc1" },
      { a: "BPS (TBDPS)", full: "t-butyldiphenylsilyl", note: "Very robust silyl ether", smiles: "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C" },
      { a: "BQ", full: "benzoquinone", note: "", smiles: "O=C1C=CC(=O)C=C1" },
      { a: "Bs", full: "brosyl (4-bromobenzenesulfonyl)", note: "", smiles: "*S(=O)(=O)c1ccc(Br)cc1" },
      { a: "BSA", full: "N,O-bis(trimethylsilyl)acetamide", note: "", smiles: "" },
      { a: "BSA", full: "bovine serum albumin", note: "", smiles: "" },
      { a: "Bt", full: "1- or 2-benzotriazolyl", note: "", smiles: "" },
      { a: "BTAF", full: "benzyltrimethylammonium fluoride", note: "", smiles: "" },
      { a: "BTEA", full: "benzyltriethylammonium", note: "", smiles: "" },
      { a: "BTEAC", full: "benzyltriethylammonium chloride", note: "", smiles: "" },
      { a: "BTFP", full: "3-bromo-1,1,1-trifluoro-propan-2-one", note: "", smiles: "" },
      { a: "BTMA", full: "benzyltrimethylammonium", note: "", smiles: "" },
      { a: "BTMSA", full: "bis(trimethylsilyl)acetylene", note: "", smiles: "C[Si](C)(C)C#C[Si](C)(C)C" },
      { a: "BTS", full: "bis(trimethylsilyl)sulfate", note: "", smiles: "" },
      { a: "BTSA", full: "benzothiazole 2-sulfonic acid", note: "", smiles: "" },
      { a: "BTSP", full: "bis(trimethylsilyl)peroxide", note: "", smiles: "C[Si](C)(C)OO[Si](C)(C)C" },
      { a: "Bu (nBu)", full: "n-butyl", note: "", smiles: "*CCCC" },
      { a: "Bz", full: "benzoyl", note: "Ester protecting group", smiles: "*C(=O)c1ccccc1" },
    ] },
    { group: "C", items: [
      { a: "18-Cr-6", full: "18-crown-6", note: "", smiles: "O1CCOCCOCCOCCOCCOCC1" },
      { a: "c", full: "cyclo", note: "", smiles: "" },
      { a: "ca", full: "circa (approximately)", note: "", smiles: "" },
      { a: "CA", full: "chloroacetyl", note: "", smiles: "*C(=O)CCl" },
      { a: "CAN", full: "cerium(IV) ammonium nitrate (cericammonium nitrate)", note: "", smiles: "" },
      { a: "cat.", full: "catalytic", note: "", smiles: "" },
      { a: "CB", full: "catecholborane", note: "", smiles: "O1c2ccccc2OB1" },
      { a: "CBS", full: "Corey-Bakshi-Shibata reagent", note: "", smiles: "" },
      { a: "Cbz (Z)", full: "benzyloxycarbonyl", note: "Amine PG, removed by hydrogenolysis", smiles: "*C(=O)OCc1ccccc1" },
      { a: "cc. or conc.", full: "concentrated", note: "", smiles: "" },
      { a: "CCE", full: "constant current electrolysis", note: "", smiles: "" },
      { a: "CDI", full: "carbonyl diimidazole", note: "Carbonyl-transfer / activation", smiles: "O=C(n1ccnc1)n1ccnc1" },
      { a: "CHD", full: "1,3 or 1,4-cyclohexadiene", note: "", smiles: "C1CC=CC=C1" },
      { a: "CHIRAPHOS", full: "2,3-bis(diphenylphosphino)butane", note: "", smiles: "CC(P(c1ccccc1)c1ccccc1)C(C)P(c1ccccc1)c1ccccc1" },
      { a: "Chx (Cy)", full: "cyclohexyl", note: "", smiles: "*C1CCCCC1" },
      { a: "CIP", full: "2-chloro-1,3-dimethylimidazolidinium hexafluorophosphate", note: "", smiles: "" },
      { a: "CM (XMET)", full: "cross metathesis", note: "Intermolecular olefin metathesis", smiles: "" },
      { a: "CMMP", full: "cyanomethylenetrimethyl phosphorane", note: "", smiles: "" },
      { a: "COD", full: "1,5-cyclooctadiene", note: "", smiles: "C1CC=CCCC=C1" },
      { a: "COT", full: "1,3,5-cyclooctatriene", note: "", smiles: "C1CC=CC=CC=C1" },
      { a: "Cp", full: "cyclopentadienyl", note: "", smiles: "*C1C=CC=C1" },
      { a: "CPTS", full: "collidinium-p-toluenesulfonate", note: "", smiles: "" },
      { a: "Cr-PILC", full: "chromium-pillared clay catalyst", note: "", smiles: "" },
      { a: "CRA", full: "complex reducing agent", note: "", smiles: "" },
      { a: "CSA", full: "camphorsulfonic acid", note: "", smiles: "CC1(C)C2CCC1(CS(=O)(=O)O)C(=O)C2" },
      { a: "CSI", full: "chlorosulfonyl isocyanate", note: "", smiles: "O=C=NS(=O)(=O)Cl" },
      { a: "CTAB", full: "cetyl trimethylammonium bromide", note: "", smiles: "" },
      { a: "CTACl", full: "cetyl trimethylammonium chloride", note: "", smiles: "" },
      { a: "CTAP", full: "cetyl trimethylammonium permanganate", note: "", smiles: "" },
    ] },
    { group: "D", items: [
      { a: "(DHQ)2PHAL", full: "bis(dihydroquinino)phthalazine", note: "", smiles: "" },
      { a: "(DHQD)2PHAL", full: "bis(dihydroquinidino)phthalazine", note: "", smiles: "" },
      { a: "d", full: "days (length of reaction time)", note: "", smiles: "" },
      { a: "DABCO", full: "1,4-diazabicyclo[2.2.2]octane", note: "Nucleophilic amine catalyst/base", smiles: "C1CN2CCN1CC2" },
      { a: "DAST", full: "diethylaminosulfur trifluoride", note: "", smiles: "CCN(CC)S(F)(F)F" },
      { a: "DATMP", full: "diethylaluminum 2,2,6,6-tetramethylpiperidide", note: "", smiles: "" },
      { a: "DBA (dba)", full: "dibenzylideneacetone", note: "Pd(0) source", smiles: "O=C(C=Cc1ccccc1)C=Cc1ccccc1" },
      { a: "DBAD", full: "di-tert-butylazodicarboxylate", note: "", smiles: "CC(C)(C)OC(=O)N=NC(=O)OC(C)(C)C" },
      { a: "DBI", full: "dibromoisocyanuric acid", note: "", smiles: "" },
      { a: "DBM", full: "dibenzoylmethane", note: "", smiles: "O=C(CC(=O)c1ccccc1)c1ccccc1" },
      { a: "DBN", full: "1,5-diazabicyclo[4.3.0]non-5-ene", note: "", smiles: "" },
      { a: "DBS", full: "dibenzosuberyl", note: "", smiles: "" },
      { a: "DBU", full: "1,8-diazabicyclo[5.4.0]undec-7-ene", note: "Strong amidine base for eliminations", smiles: "C1CCC2=NCCCN2CC1" },
      { a: "DCA", full: "9,10-dicyanoanthracene", note: "", smiles: "N#Cc1c2ccccc2c(C#N)c2ccccc12" },
      { a: "DCB", full: "1,2-dichlorobenzene", note: "", smiles: "Clc1ccccc1Cl" },
      { a: "DCC", full: "dicyclohexylcarbodiimide", note: "Amide/ester coupling agent", smiles: "C1CCCCC1N=C=NC1CCCCC1" },
      { a: "DCE", full: "1,1-dichloroethane", note: "Higher-boiling chlorinated solvent", smiles: "CC(Cl)Cl" },
      { a: "DCM", full: "dichloromethane", note: "CH₂Cl₂, common solvent", smiles: "ClCCl" },
      { a: "DCN", full: "1,4-dicyanonaphthalene", note: "", smiles: "" },
      { a: "Dcpm", full: "dicyclopropylmethyl", note: "", smiles: "" },
      { a: "DCU", full: "N,N'-dicyclohexylurea", note: "", smiles: "C1CCCCC1NC(=O)NC1CCCCC1" },
      { a: "DDQ", full: "2,3-dichloro-5,6-dicyano-1,4-benzoquinone", note: "Dehydrogenation / PMB removal", smiles: "O=C1C(Cl)=C(Cl)C(=O)C(C#N)=C1C#N" },
      { a: "de", full: "diastereomeric excess", note: "", smiles: "" },
      { a: "DEAD", full: "diethyl azodicarboxylate", note: "Mitsunobu reagent", smiles: "CCOC(=O)N=NC(=O)OCC" },
      { a: "DEIPS", full: "diethylisopropylsilyl", note: "", smiles: "" },
      { a: "delta", full: "heat", note: "", smiles: "" },
      { a: "DEPBT", full: "3-(diethoxyphosphoryloxy)-1,2,3-benzotriazin-4(3H)-one", note: "", smiles: "" },
      { a: "DET", full: "diethyl tartrate", note: "", smiles: "CCOC(=O)C(O)C(O)C(=O)OCC" },
      { a: "DHP", full: "3,4-dihydro-2H-pyran", note: "", smiles: "O1CCCC=C1" },
      { a: "DHQ", full: "dihydroquinine", note: "", smiles: "" },
      { a: "DHQD", full: "dihydroquinidine", note: "", smiles: "" },
      { a: "DIAD", full: "diisopropyl azodicarboxylate", note: "Mitsunobu reagent", smiles: "CC(C)OC(=O)N=NC(=O)OC(C)C" },
      { a: "DIB (BAIB or PIDA)", full: "(diacetoxyiodo)benzene", note: "", smiles: "" },
      { a: "DIBAL (DIBAH, DIBAL-H)", full: "diisobutylaluminum hydride", note: "", smiles: "CC(C)C[AlH]CC(C)C" },
      { a: "DIC", full: "diisopropyl carbodiimide", note: "Carbodiimide coupling reagent", smiles: "CC(C)N=C=NC(C)C" },
      { a: "diop", full: "4,5-bis-[(diphenylphosphanyl)methyl]-2,2-dimethyl-[1,3]dioxolane", note: "", smiles: "" },
      { a: "DIPAMP", full: "1,2-bis(o-anisylphenylphosphino)ethane", note: "", smiles: "COc1ccccc1P(CCP(c1ccccc1)c1ccccc1OC)c1ccccc1" },
      { a: "DIPEA (Hunig's base)", full: "diisopropylethylamine", note: "", smiles: "CCN(C(C)C)C(C)C" },
      { a: "DIPT", full: "diisopropyl tartrate", note: "", smiles: "CC(C)OC(=O)C(O)C(O)C(=O)OC(C)C" },
      { a: "DLP", full: "dilauroyl peroxide", note: "", smiles: "" },
      { a: "DMA (DMAC)", full: "N,N-dimethylacetamide", note: "", smiles: "CC(=O)N(C)C" },
      { a: "DMAD", full: "dimethyl acetylene dicarboxylate", note: "", smiles: "COC(=O)C#CC(=O)OC" },
      { a: "DMAP", full: "N,N-4-dimethylaminopyridine", note: "Acyl-transfer catalyst", smiles: "CN(C)c1ccncc1" },
      { a: "DMB", full: "m-dimethoxybenzene", note: "", smiles: "COc1cccc(OC)c1" },
      { a: "DMDO", full: "dimethyl dioxirane", note: "", smiles: "CC1(C)OO1" },
      { a: "DME", full: "1,2-dimethoxyethane", note: "", smiles: "COCCOC" },
      { a: "DMF", full: "N,N-dimethylformamide", note: "Polar aprotic solvent", smiles: "CN(C)C=O" },
      { a: "DMI", full: "1,3-dimethylimidazolidin-2-one", note: "", smiles: "O=C1N(C)CCN1C" },
      { a: "DMP", full: "Dess-Martin periodinane", note: "Alcohol → aldehyde/ketone, mild", smiles: "CC(=O)OI1(OC(C)=O)(OC(C)=O)OC(=O)c2ccccc21" },
      { a: "DMPS", full: "dimethylphenylsilyl", note: "", smiles: "" },
      { a: "DMPU", full: "1,3-dimethyl-3,4,5,6-tetrahydro-2(1H)-pyrimidone", note: "Safer HMPA alternative", smiles: "O=C1N(C)CCCN1C" },
      { a: "DMS", full: "dimethylsulfide", note: "", smiles: "CSC" },
      { a: "DMSO", full: "dimethylsulfoxide", note: "Polar aprotic; Swern oxidant", smiles: "CS(C)=O" },
      { a: "DMT", full: "4,4'-dimethoxytrityl", note: "", smiles: "*C(c1ccc(OC)cc1)(c1ccc(OC)cc1)c1ccccc1" },
      { a: "DMTMM", full: "4-(4,6-dimethoxy[1,3,5]triazin-2-yl)-4-methylmorpholinium chloride", note: "", smiles: "" },
      { a: "DMTr", full: "4,4'-dimethyltrityl", note: "", smiles: "" },
      { a: "DMTSF", full: "dimethyl(methylthio)sulfonium tetrafluoroborate", note: "", smiles: "C[S+](C)SC.[B-](F)(F)(F)F" },
      { a: "DMTST", full: "(dimethylthio)methylsulfonium trifluoromethanesulfonate", note: "", smiles: "" },
      { a: "DNA", full: "deoxyribonucleic acid", note: "", smiles: "" },
      { a: "DPA (DIPA)", full: "diisopropylamine", note: "", smiles: "CC(C)NC(C)C" },
      { a: "DPBP", full: "2,2'-bis(diphenylphosphino)biphenyl", note: "", smiles: "c1ccc(P(c2ccccc2)c2ccccc2-c2ccccc2P(c2ccccc2)c2ccccc2)cc1" },
      { a: "DPDC", full: "diisopropyl peroxydicarbonate", note: "", smiles: "" },
      { a: "DPDM", full: "diphenyl diazomethane", note: "", smiles: "[N-]=[N+]=C(c1ccccc1)c1ccccc1" },
      { a: "DPEDA", full: "1,2-diamino-1,2-diphenylethane", note: "", smiles: "NC(c1ccccc1)C(N)c1ccccc1" },
      { a: "DPIBF", full: "diphenylisobenzofuran", note: "", smiles: "c1ccc(-c2c3ccccc3c(-c3ccccc3)o2)cc1" },
      { a: "DPPA", full: "diphenylphosphoryl azide (diphenylphosphorazidate)", note: "", smiles: "O=P(Oc1ccccc1)(Oc1ccccc1)N=[N+]=[N-]" },
      { a: "Dppb (ddpb)", full: "1,4-bis(diphenylphosphino)butane", note: "", smiles: "c1ccc(P(CCCCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1" },
      { a: "dppe", full: "1,2-bis(diphenylphosphino)ethane", note: "", smiles: "c1ccc(P(CCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1" },
      { a: "dppf", full: "1,1'-bis(diphenylphosphino)ferrocene", note: "Bidentate phosphine ligand", smiles: "" },
      { a: "dppm", full: "bis(diphenylphosphino)methane", note: "", smiles: "c1ccc(P(CP(c2ccccc2)c2ccccc2)c2ccccc2)cc1" },
      { a: "dppp", full: "1,3-bis(diphenylphosphino)propane", note: "", smiles: "c1ccc(P(CCCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1" },
      { a: "DPS (TBDPS or BPS)", full: "t-butyldiphenylsilyl", note: "Very robust silyl ether", smiles: "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C" },
      { a: "DPTC", full: "O,O'-di(2'-pyridyl)thiocarbonate", note: "", smiles: "" },
      { a: "dr", full: "diastereomeric ratio", note: "Stereoselectivity measures", smiles: "" },
      { a: "DTBAD (DBAD)", full: "di-tert-butyl azodicarboxylate", note: "", smiles: "CC(C)(C)OC(=O)N=NC(=O)OC(C)(C)C" },
      { a: "DTBB", full: "4,4'-di-tert-butylbiphenyl", note: "", smiles: "CC(C)(C)c1ccc(-c2ccc(C(C)(C)C)cc2)cc1" },
      { a: "DTBMP", full: "2,6-di-tert-butyl-4-methylpyridine", note: "", smiles: "Cc1cc(C(C)(C)C)nc(C(C)(C)C)c1" },
      { a: "DTBP", full: "2,6-di-tert-butylpyridine", note: "", smiles: "CC(C)(C)c1cccc(C(C)(C)C)n1" },
      { a: "DTE", full: "1,4-dithioerythritol", note: "", smiles: "SCC(O)C(O)CS" },
      { a: "DVS", full: "1,3-divinyl-1,1,3,3-tetramethyldisiloxane", note: "", smiles: "C=C[Si](C)(C)O[Si](C)(C)C=C" },
    ] },
    { group: "E", items: [
      { a: "E+", full: "electrophile (denotes any electrophile in general)", note: "", smiles: "" },
      { a: "E2", full: "bimolecular elimination", note: "Elimination mechanisms", smiles: "" },
      { a: "ED", full: "effective dosage", note: "", smiles: "" },
      { a: "EDA", full: "ethyl diazoacetate", note: "", smiles: "CCOC(=O)C=[N+]=[N-]" },
      { a: "EDC (EDAC)", full: "1-ethyl-3-(3-dimethylaminopropyl)carbodiimide", note: "Water-soluble coupling agent", smiles: "CCN=C=NCCCN(C)C" },
      { a: "EDCI", full: "1-ethyl-3-(3-dimethylaminopropyl)carbodiimide hydrochloride", note: "Water-soluble coupling agent", smiles: "CCN=C=NCCCN(C)C" },
      { a: "EDCP", full: "2,3-bis-phosphonopentanedioic acid", note: "", smiles: "" },
      { a: "EDDA", full: "ethylenediamine diacetate", note: "", smiles: "" },
      { a: "EDG", full: "electron-donating group", note: "", smiles: "" },
      { a: "EDTA", full: "ethylenediamine tetraacetic acid", note: "", smiles: "OC(=O)CN(CC(=O)O)CCN(CC(=O)O)CC(=O)O" },
      { a: "ee", full: "enantiomeric excess", note: "Stereoselectivity measures", smiles: "" },
      { a: "EE", full: "ethoxyethyl", note: "Stereoselectivity measures", smiles: "*C(C)OCC" },
      { a: "Ei", full: "intramolecular syn elimination", note: "", smiles: "" },
      { a: "en", full: "ethylenediamine", note: "", smiles: "NCCN" },
      { a: "EOM", full: "ethoxymethyl", note: "", smiles: "*COCC" },
      { a: "ESR", full: "electron spin resonance (spectroscopy)", note: "", smiles: "" },
      { a: "Et", full: "ethyl", note: "", smiles: "*CC" },
      { a: "ETSA", full: "ethyl trimethylsilylacetate", note: "", smiles: "" },
      { a: "EVE", full: "ethyl vinyl ether", note: "", smiles: "C=COCC" },
      { a: "EWG", full: "electron-withdrawing group", note: "", smiles: "" },
    ] },
    { group: "F", items: [
      { a: "Fc", full: "ferrocenyl", note: "", smiles: "" },
      { a: "FDP", full: "fructose-1,6-diphosphate", note: "", smiles: "" },
      { a: "FDPP", full: "pentafluorophenyl diphenylphosphinate", note: "", smiles: "" },
      { a: "Fl", full: "fluorenyl", note: "", smiles: "*C1c2ccccc2-c2ccccc21" },
      { a: "FMO", full: "frontier molecular orbital (theory)", note: "", smiles: "" },
      { a: "Fmoc", full: "9-fluorenylmethoxycarbonyl", note: "Base-labile amine PG (SPPS)", smiles: "*C(=O)OCC1c2ccccc2-c2ccccc21" },
      { a: "fod", full: "6,6,7,7,8,8,8-heptafluoro-2,2-dimethyl-3,5-octanedione", note: "", smiles: "" },
      { a: "fp", full: "flash point", note: "", smiles: "" },
      { a: "FSM", full: "mesoporous silica", note: "", smiles: "" },
      { a: "FTT", full: "1-fluoro-2,4,6-trimethylpyridinium triflate", note: "", smiles: "" },
      { a: "FVP", full: "flash vacuum pyrolysis", note: "", smiles: "" },
    ] },
    { group: "G", items: [
      { a: "GEBC", full: "gel entrapped base catalyst", note: "", smiles: "" },
    ] },
    { group: "H", items: [
      { a: "h", full: "hours (length of reaction time)", note: "", smiles: "" },
      { a: "h-nu", full: "irradiation with light", note: "", smiles: "" },
      { a: "HATU", full: "O-(7-azabenzotriazol-1-yl)-N,N,N',N'-tetramethyluronium hexafluorophosphate", note: "Peptide coupling agent", smiles: "" },
      { a: "Het", full: "heterocycle", note: "", smiles: "" },
      { a: "hfacac", full: "hexafluoroacetylacetone", note: "", smiles: "O=C(CC(=O)C(F)(F)F)C(F)(F)F" },
      { a: "HFIP", full: "1,1,1,3,3,3-hexafluoro-2-propanol (hexafluoroisopropanol)", note: "", smiles: "OC(C(F)(F)F)C(F)(F)F" },
      { a: "HGK", full: "4-hydroxy-2-ketoglutarate", note: "", smiles: "" },
      { a: "Hgmm", full: "millimeter of mercury (760 Hgmm = 1 atm = 760 Torr)", note: "", smiles: "" },
      { a: "HLE", full: "horse liver esterase", note: "", smiles: "" },
      { a: "Hmb", full: "2-hydroxy-4-methoxybenzyl", note: "", smiles: "" },
      { a: "HMDS", full: "1,1,1,3,3,3-hexamethyldisilazane", note: "", smiles: "C[Si](C)(C)N[Si](C)(C)C" },
      { a: "HMPA", full: "hexamethylphosphoric acid triamide (hexamethylphosphoramide)", note: "Strong cation-solvating additive", smiles: "O=P(N(C)C)(N(C)C)N(C)C" },
      { a: "HMPT", full: "hexamethylphosphorous triamide", note: "", smiles: "P(N(C)C)(N(C)C)N(C)C" },
      { a: "HOAt", full: "1-hydroxy-7-azabenzotriazole", note: "", smiles: "On1nnc2ncccc21" },
      { a: "HOBt (HOBT)", full: "1-hydroxybenzotriazole", note: "Additive suppressing racemization", smiles: "On1nnc2ccccc21" },
      { a: "HOMO", full: "highest occupied molecular orbital", note: "", smiles: "" },
      { a: "HOSu", full: "N-hydroxysuccinimide", note: "", smiles: "O=C1CCC(=O)N1O" },
      { a: "HPLC", full: "high-pressure liquid chromatography", note: "", smiles: "" },
      { a: "HWE", full: "Horner-Wadsworth-Emmons", note: "", smiles: "" },
    ] },
    { group: "I", items: [
      { a: "i", full: "iso", note: "", smiles: "" },
      { a: "IBA", full: "2-iodosobenzoic acid", note: "", smiles: "" },
      { a: "IBX", full: "o-iodoxybenzoic acid", note: "Alcohol → carbonyl oxidant", smiles: "" },
      { a: "IDCP", full: "bis(2,4,6-collidine)iodonium perchlorate", note: "", smiles: "" },
      { a: "Imid (Im)", full: "imidazole", note: "", smiles: "c1c[nH]cn1" },
      { a: "INOC", full: "intramolecular nitrile oxide cycloaddition", note: "", smiles: "" },
      { a: "IPA", full: "isopropyl alcohol", note: "", smiles: "CC(C)O" },
      { a: "Ipc", full: "isopinocamphenyl", note: "", smiles: "" },
      { a: "IR", full: "infrared spectroscopy", note: "", smiles: "" },
    ] },
    { group: "K", items: [
      { a: "K-10", full: "a type of Montmorillonite clay", note: "", smiles: "" },
      { a: "KDA", full: "potassium diisopropylamide", note: "", smiles: "" },
      { a: "KHMDS", full: "potassium bis(trimethylsilyl)amide", note: "Hindered amide base; often thermodynamic enolate", smiles: "[K]N([Si](C)(C)C)[Si](C)(C)C" },
      { a: "KSF", full: "a type of Montmorillonite clay", note: "", smiles: "" },
    ] },
    { group: "L", items: [
      { a: "L", full: "ligand", note: "", smiles: "" },
      { a: "L-selectride", full: "lithium tri-sec-butylborohydride", note: "Bulky, stereoselective hydride", smiles: "[Li][BH](C(C)CC)(C(C)CC)C(C)CC" },
      { a: "L.R.", full: "Lawesson's reagent", note: "", smiles: "" },
      { a: "LA", full: "Lewis acid", note: "", smiles: "" },
      { a: "LAB", full: "lithium amidotrihydroborate", note: "", smiles: "[Li][BH3]N" },
      { a: "LAH", full: "lithium aluminum hydride", note: "Powerful hydride reductant", smiles: "[Li+].[AlH4-]" },
      { a: "LD50", full: "dose lethal to 50% of test subjects", note: "", smiles: "" },
      { a: "LDA", full: "lithium diisopropylamide", note: "Strong, non-nucleophilic base for kinetic enolates", smiles: "[Li]N(C(C)C)C(C)C" },
      { a: "LDBB", full: "lithium 4,4'-t-butylbiphenylide", note: "", smiles: "" },
      { a: "LDE", full: "lithium diethylamide", note: "", smiles: "" },
      { a: "LDPE", full: "lithium perchlorate-diethyl etherate", note: "", smiles: "" },
      { a: "LHMDS (LiHMDS)", full: "lithium bis(trimethylsilyl)amide", note: "Bulky amide base (also NaHMDS, KHMDS)", smiles: "[Li]N([Si](C)(C)C)[Si](C)(C)C" },
      { a: "LICA", full: "lithium isopropylcyclohexylamide", note: "", smiles: "" },
      { a: "LICKOR (super base)", full: "butyllithium-potassium tert-butoxide", note: "", smiles: "" },
      { a: "liq.", full: "liquid", note: "", smiles: "" },
      { a: "LiTMP (LTMP)", full: "lithium 2,2,6,6-tetramethylpiperidide", note: "", smiles: "[Li]N1C(C)(C)CCCC1(C)C" },
      { a: "LPT", full: "lithium pyrrolidotrihydroborate", note: "", smiles: "" },
      { a: "LTA", full: "lead tetraacetate", note: "", smiles: "" },
      { a: "LUMO", full: "lowest unoccupied molecular orbital", note: "", smiles: "" },
      { a: "lut", full: "2,6-lutidine", note: "", smiles: "Cc1cccc(C)n1" },
    ] },
    { group: "M", items: [
      { a: "m", full: "meta", note: "", smiles: "" },
      { a: "m-CPBA", full: "meta-chloroperbenzoic acid", note: "Epoxidation, Baeyer–Villiger", smiles: "O=C(OO)c1cccc(Cl)c1" },
      { a: "MA", full: "maleic anhydride", note: "", smiles: "O=C1OC(=O)C=C1" },
      { a: "MAD", full: "methyl aluminum bis(2,6-di-t-butyl-4-methylphenoxide)", note: "", smiles: "" },
      { a: "MAT", full: "methyl aluminum bis(2,4,6-tri-t-butylphenoxide)", note: "", smiles: "" },
      { a: "MBT", full: "2-mercaptobenzothiazole", note: "", smiles: "" },
      { a: "Me", full: "methyl", note: "", smiles: "*C" },
      { a: "MEM", full: "(2-methoxyethoxy)methyl", note: "", smiles: "*COCCOC" },
      { a: "MEPY", full: "methyl 2-pyrrolidone-5(S)-carboxylate", note: "", smiles: "" },
      { a: "Mes", full: "mesityl", note: "", smiles: "*c1c(C)cc(C)cc1C" },
      { a: "mesal", full: "N-methylsalicylaldimine", note: "", smiles: "" },
      { a: "MIC", full: "methyl isocyanate", note: "", smiles: "CN=C=O" },
      { a: "MMPP (MMPT)", full: "magnesium monoperoxyphthalate", note: "", smiles: "" },
      { a: "MOM", full: "methoxymethyl", note: "Acetal-type alcohol PG", smiles: "*COC" },
      { a: "MoOPH", full: "oxodiperoxomolybdenum(pyridine)(hexamethylphosphoric triamide)", note: "", smiles: "" },
      { a: "mp", full: "melting point", note: "", smiles: "" },
      { a: "MPa", full: "megapascal = 10^6 Pa = 10 atm", note: "", smiles: "" },
      { a: "MPD (NMP)", full: "N-methyl-2-pyrrolidinone", note: "High-boiling polar aprotic solvent", smiles: "O=C1CCCN1C" },
      { a: "MPM", full: "methoxy(phenylthio)methyl", note: "Alcohol PG, removed by DDQ", smiles: "" },
      { a: "MPM (PMB)", full: "p-methoxybenzyl", note: "Alcohol PG, removed by DDQ", smiles: "*Cc1ccc(OC)cc1" },
      { a: "MPPC", full: "N-methyl piperidinium chlorochromate", note: "", smiles: "" },
      { a: "Ms", full: "mesyl (methanesulfonyl)", note: "Leaving group (mesylate)", smiles: "*S(=O)(=O)C" },
      { a: "MS", full: "mass spectrometry", note: "Leaving group (mesylate)", smiles: "" },
      { a: "MS", full: "molecular sieves", note: "Leaving group (mesylate)", smiles: "" },
      { a: "MSA", full: "methanesulfonic acid", note: "", smiles: "CS(=O)(=O)O" },
      { a: "MSH", full: "o-mesitylenesulfonyl hydroxylamine", note: "", smiles: "Cc1cc(C)c(S(=O)(=O)ON)c(C)c1" },
      { a: "MSTFA", full: "N-methyl-N-(trimethylsilyl)trifluoroacetamide", note: "", smiles: "" },
      { a: "MTAD", full: "N-methyltriazolinedione", note: "", smiles: "O=C1N(C)C(=O)N=N1" },
      { a: "MTEE (MTBE)", full: "methyl t-butyl ether", note: "", smiles: "COC(C)(C)C" },
      { a: "MTM", full: "methylthiomethyl", note: "", smiles: "*CSC" },
      { a: "MTO", full: "methyltrioxorhenium", note: "", smiles: "" },
      { a: "Mtr", full: "(4-methoxy-2,3,6-trimethylphenyl)sulfonyl", note: "", smiles: "" },
      { a: "MVK", full: "methyl vinyl ketone", note: "", smiles: "C=CC(C)=O" },
      { a: "mw", full: "microwave", note: "", smiles: "" },
    ] },
    { group: "N", items: [
      { a: "n", full: "normal (unbranched alkyl chain)", note: "", smiles: "" },
      { a: "NADPH", full: "nicotinamide adenine dinucleotide phosphate", note: "", smiles: "" },
      { a: "NaHMDS", full: "sodium bis(trimethylsilyl)amide", note: "Hindered amide base", smiles: "[Na]N([Si](C)(C)C)[Si](C)(C)C" },
      { a: "Naph (Np)", full: "naphthyl", note: "", smiles: "*c1cccc2ccccc12" },
      { a: "NBA", full: "N-bromoacetamide", note: "", smiles: "CC(=O)NBr" },
      { a: "NBD (nbd)", full: "norbornadiene", note: "", smiles: "" },
      { a: "NBS", full: "N-bromosuccinimide", note: "Allylic/benzylic bromination; Br⁺ source", smiles: "O=C1CCC(=O)N1Br" },
      { a: "NCS", full: "N-chlorosuccinimide", note: "Chlorinating reagent", smiles: "O=C1CCC(=O)N1Cl" },
      { a: "Nf", full: "nonafluorobutanesulfonyl", note: "", smiles: "" },
      { a: "NHPI", full: "N-hydroxyphthalimide", note: "", smiles: "O=C1c2ccccc2C(=O)N1O" },
      { a: "NIS", full: "N-iodosuccinimide", note: "", smiles: "O=C1CCC(=O)N1I" },
      { a: "NMM", full: "N-methylmorpholine", note: "", smiles: "CN1CCOCC1" },
      { a: "NMO", full: "N-methylmorpholine oxide", note: "Co-oxidant (with OsO₄, TPAP)", smiles: "C[N+]1([O-])CCOCC1" },
      { a: "NMP", full: "N-methyl-2-pyrrolidinone", note: "High-boiling polar aprotic solvent", smiles: "O=C1CCCN1C" },
      { a: "NMR", full: "nuclear magnetic resonance", note: "", smiles: "" },
      { a: "NORPHOS", full: "bis(diphenylphosphino)bicyclo[2.2.1]hept-5-ene", note: "", smiles: "" },
      { a: "Nos", full: "4-nitrobenzenesulfonyl", note: "", smiles: "*S(=O)(=O)c1ccc(cc1)[N+](=O)[O-]" },
      { a: "NPM", full: "N-phenylmaleimide", note: "", smiles: "O=C1C=CC(=O)N1c1ccccc1" },
      { a: "NR", full: "no reaction", note: "", smiles: "" },
      { a: "Ns", full: "2-nitrobenzenesulfonyl", note: "", smiles: "*S(=O)(=O)c1ccccc1[N+](=O)[O-]" },
      { a: "NSAID", full: "non steroidal anti-inflammatory drug", note: "", smiles: "" },
      { a: "Nuc", full: "nucleophile (general)", note: "", smiles: "" },
    ] },
    { group: "O", items: [
      { a: "o", full: "ortho", note: "", smiles: "" },
      { a: "Oxone", full: "potassium peroxymonosulfate", note: "Oxidant; dioxirane source (Shi epox.)", smiles: "" },
    ] },
    { group: "P", items: [
      { a: "p", full: "para", note: "", smiles: "" },
      { a: "P.T.", full: "proton transfer", note: "", smiles: "" },
      { a: "PAP", full: "2,8,9-trialkyl-2,5,8,9-tetraaza-1-phospha-bicyclo[3.3.3]undecane", note: "", smiles: "" },
      { a: "PBP", full: "pyridinium bromide perbromide", note: "", smiles: "" },
      { a: "PCC", full: "pyridinium chlorochromate", note: "Alcohol oxidation (to aldehyde)", smiles: "" },
      { a: "PDC", full: "pyridinium dichromate", note: "Alcohol oxidation", smiles: "" },
      { a: "PEG", full: "polyethylene glycol", note: "", smiles: "" },
      { a: "Pf", full: "9-phenylfluorenyl", note: "", smiles: "*C1(c2ccccc2)c2ccccc2-c2ccccc21" },
      { a: "pfb", full: "perfluorobutyrate", note: "", smiles: "" },
      { a: "Ph", full: "phenyl", note: "", smiles: "*c1ccccc1" },
      { a: "PHAL", full: "phthalazine", note: "", smiles: "c1ccc2cnncc2c1" },
      { a: "phen", full: "9,10-phenanthroline", note: "", smiles: "c1ccc2ccc3cccnc3c2n1" },
      { a: "Phth", full: "phthaloyl", note: "", smiles: "*N1C(=O)c2ccccc2C1=O" },
      { a: "pic", full: "2-pyridinecarboxylate", note: "", smiles: "" },
      { a: "PIDA (BAIB or DIB)", full: "phenyliodonium diacetate", note: "", smiles: "" },
      { a: "PIFA", full: "phenyliodonium bis(trifluoroacetate)", note: "", smiles: "" },
      { a: "Piv", full: "pivaloyl", note: "", smiles: "*C(=O)C(C)(C)C" },
      { a: "PLE", full: "pig liver esterase", note: "", smiles: "" },
      { a: "PMB (MPM)", full: "p-methoxybenzyl", note: "Alcohol PG, removed by DDQ", smiles: "*Cc1ccc(OC)cc1" },
      { a: "PMP", full: "4-methoxyphenyl", note: "", smiles: "*c1ccc(OC)cc1" },
      { a: "PMP", full: "1,2,2,6,6-pentamethylpiperidine", note: "", smiles: "CN1C(C)(C)CCCC1(C)C" },
      { a: "PNB", full: "p-nitrobenzyl", note: "", smiles: "*Cc1ccc(cc1)[N+](=O)[O-]" },
      { a: "PNZ", full: "p-nitrobenzyloxycarbonyl", note: "", smiles: "*C(=O)OCc1ccc(cc1)[N+](=O)[O-]" },
      { a: "PPA", full: "polyphosphoric acid", note: "", smiles: "" },
      { a: "PPI", full: "2-phenyl-2-(2-pyridyl)-2H-imidazole", note: "", smiles: "" },
      { a: "PPL", full: "pig pancreatic lipase", note: "", smiles: "" },
      { a: "PPO", full: "4-(3-phenylpropyl)pyridine-N-oxide", note: "", smiles: "" },
      { a: "PPSE", full: "polyphosphoric acid trimethylsilyl ester", note: "", smiles: "" },
      { a: "PPTS", full: "pyridinium p-toluenesulfonate", note: "Mild acid catalyst", smiles: "" },
      { a: "Pr", full: "propyl", note: "", smiles: "*CCC" },
      { a: "psi", full: "pounds per square inch", note: "", smiles: "" },
      { a: "PT", full: "1-phenyl-1H-tetrazol-yl", note: "", smiles: "" },
      { a: "PTAB", full: "phenyltrimethylammonium perbromide", note: "", smiles: "" },
      { a: "PTC", full: "phase transfer catalyst", note: "", smiles: "" },
      { a: "PTMSE", full: "(2-phenyl-2-trimethylsilyl)ethyl", note: "", smiles: "" },
      { a: "PTSA (or TsOH)", full: "p-toluenesulfonic acid", note: "", smiles: "Cc1ccc(S(=O)(=O)O)cc1" },
      { a: "PVP", full: "poly(4-vinylpyridine)", note: "", smiles: "" },
      { a: "Py (pyr)", full: "pyridine", note: "", smiles: "c1ccncc1" },
    ] },
    { group: "R", items: [
      { a: "r.t.", full: "room temperature", note: "", smiles: "" },
      { a: "rac", full: "racemic", note: "", smiles: "" },
      { a: "RAMP", full: "(R)-1-amino-2-(methoxymethyl)pyrrolidine", note: "", smiles: "" },
      { a: "RaNi", full: "Raney nickel", note: "", smiles: "[Ni]" },
      { a: "RB", full: "Rose Bengal", note: "", smiles: "" },
      { a: "RCAM", full: "ring-closing alkyne metathesis", note: "", smiles: "" },
      { a: "RCM", full: "ring-closing metathesis", note: "Forms rings via olefin metathesis", smiles: "" },
      { a: "Rds (RDS)", full: "rate-determining step", note: "", smiles: "" },
      { a: "Red-Al", full: "sodium bis(2-methoxyethoxy)aluminum hydride", note: "Soluble hydride reductant", smiles: "[Na][AlH2](OCCOC)OCCOC" },
      { a: "Rf", full: "perfluoroalkyl group", note: "", smiles: "" },
      { a: "Rf", full: "retention factor in chromatography", note: "", smiles: "" },
      { a: "Rham", full: "rhamnosyl", note: "", smiles: "" },
      { a: "ROM", full: "ring-opening metathesis", note: "", smiles: "" },
      { a: "ROMP", full: "ring-opening metathesis polymerization", note: "", smiles: "" },
      { a: "Rose Bengal (RB)", full: "2,4,5,7-tetraiodo-3',4',5',6'-tetrachlorofluorescein disodium salt", note: "", smiles: "" },
    ] },
    { group: "S", items: [
      { a: "s", full: "seconds (length of reaction time)", note: "", smiles: "" },
      { a: "S,S-chiraphos", full: "(S,S)-2,3-bis(diphenylphosphino)butane", note: "", smiles: "" },
      { a: "Salen", full: "N,N'-ethylenebis(salicylideneiminato)", note: "Metal-complex ligand (Jacobsen)", smiles: "Oc1ccccc1C=NCCN=Cc1ccccc1O" },
      { a: "salophen", full: "o-phenylenebis(salicylideneiminato)", note: "", smiles: "" },
      { a: "SAMP", full: "(S)-1-amino-2-(methoxymethyl)pyrrolidine", note: "", smiles: "" },
      { a: "SC CO2", full: "supercritical carbon dioxide", note: "", smiles: "" },
      { a: "SDS", full: "sodium dodecylsulfate", note: "", smiles: "" },
      { a: "sec", full: "secondary", note: "", smiles: "" },
      { a: "SEM", full: "2-(trimethylsilyl)ethoxymethyl", note: "", smiles: "*COCC[Si](C)(C)C" },
      { a: "SES", full: "2-[(trimethylsilyl)ethyl]sulfonyl", note: "", smiles: "" },
      { a: "SET", full: "single electron transfer", note: "One-electron redox step", smiles: "" },
      { a: "Sia", full: "1,2-dimethylpropyl (secondary isoamyl)", note: "", smiles: "*C(C)C(C)C" },
      { a: "SPB", full: "sodium perborate", note: "", smiles: "" },
    ] },
    { group: "T", items: [
      { a: "TADDOL", full: "2,2-dimethyl-alpha,alpha,alpha',alpha'-tetraaryl-1,3-dioxolane-4,5-dimethanol", note: "", smiles: "" },
      { a: "TASF", full: "tris(diethylamino)sulfonium difluorotrimethylsilicate", note: "", smiles: "" },
      { a: "TBAB", full: "tetra-n-butylammonium bromide", note: "", smiles: "CCCC[N+](CCCC)(CCCC)CCCC.[Br-]" },
      { a: "TBAF", full: "tetra-n-butylammonium fluoride", note: "Removes silyl protecting groups", smiles: "CCCC[N+](CCCC)(CCCC)CCCC.[F-]" },
      { a: "TBAI", full: "tetra-n-butylammonium iodide", note: "", smiles: "CCCC[N+](CCCC)(CCCC)CCCC.[I-]" },
      { a: "TBCO", full: "tetrabromocyclohexadienone", note: "", smiles: "" },
      { a: "TBDMS (TBS)", full: "t-butyldimethylsilyl", note: "Robust silyl ether PG", smiles: "*[Si](C)(C)C(C)(C)C" },
      { a: "TBDPS (BPS)", full: "t-butyldiphenylsilyl", note: "Very robust silyl ether", smiles: "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C" },
      { a: "TBH", full: "tert-butyl hypochlorite", note: "", smiles: "CC(C)(C)OCl" },
      { a: "TBHP", full: "tert-butyl hydroperoxide", note: "", smiles: "CC(C)(C)OO" },
      { a: "TBP", full: "tributylphosphine", note: "", smiles: "CCCCP(CCCC)CCCC" },
      { a: "TBT", full: "1-tert-butyl-1H-tetrazol-5-yl", note: "", smiles: "" },
      { a: "TBTH", full: "tributyltin hydride", note: "", smiles: "CCCC[SnH](CCCC)CCCC" },
      { a: "TBTSP", full: "t-butyl trimethylsilyl peroxide", note: "", smiles: "" },
      { a: "TCCA", full: "trichloroisocyanuric acid", note: "", smiles: "O=C1N(Cl)C(=O)N(Cl)C(=O)N1Cl" },
      { a: "TCDI", full: "thiocarbonyl diimidazole", note: "", smiles: "S=C(n1ccnc1)n1ccnc1" },
      { a: "TCNE", full: "tetracyanoethylene", note: "", smiles: "N#CC(C#N)=C(C#N)C#N" },
      { a: "TCNQ", full: "7,7,8,8-tetracyano-para-quinodimethane", note: "", smiles: "N#CC(C#N)=C1C=CC(=C(C#N)C#N)C=C1" },
      { a: "TDS", full: "dimethyl thexylsilyl", note: "", smiles: "*[Si](C)(C)C(C)C(C)(C)C" },
      { a: "TEA", full: "triethylamine", note: "", smiles: "CCN(CC)CC" },
      { a: "TEBACl", full: "benzyltrimethylammonium chloride", note: "", smiles: "" },
      { a: "TEMPO", full: "2,2,6,6-tetramethyl-1-piperidinyloxy free radical", note: "Radical alcohol-oxidation catalyst", smiles: "CC1(C)CCCC(C)(C)N1[O]" },
      { a: "Teoc", full: "2-(trimethylsilyl)ethoxycarbonyl", note: "", smiles: "*C(=O)OCC[Si](C)(C)C" },
      { a: "TEP", full: "triethylphosphite", note: "", smiles: "CCOP(OCC)OCC" },
      { a: "TES", full: "triethylsilyl", note: "", smiles: "*[Si](CC)(CC)CC" },
      { a: "Tf", full: "trifluoromethanesulfonyl", note: "Excellent leaving group (triflate)", smiles: "*S(=O)(=O)C(F)(F)F" },
      { a: "TFA", full: "trifluoroacetic acid", note: "Acid; Boc deprotection", smiles: "OC(=O)C(F)(F)F" },
      { a: "Tfa", full: "trifluoroacetamide", note: "Acid; Boc deprotection", smiles: "NC(=O)C(F)(F)F" },
      { a: "TFAA", full: "trifluoroacetic anhydride", note: "", smiles: "O=C(OC(=O)C(F)(F)F)C(F)(F)F" },
      { a: "TFE", full: "2,2,2-trifluoroethanol", note: "", smiles: "OCC(F)(F)F" },
      { a: "TFMSA", full: "trifluoromethanesulfonic acid (triflic acid)", note: "", smiles: "OS(=O)(=O)C(F)(F)F" },
      { a: "TFP", full: "tris(2-furyl)phosphine", note: "", smiles: "c1ccc(o1)P(c1ccco1)c1ccco1" },
      { a: "Th", full: "2-thienyl", note: "", smiles: "" },
      { a: "thexyl", full: "1,1,2-trimethylpropyl", note: "", smiles: "*C(C)(C)C(C)C" },
      { a: "THF", full: "tetrahydrofuran", note: "Common ethereal solvent", smiles: "C1CCOC1" },
      { a: "THP", full: "2-tetrahydropyranyl", note: "Acid-labile alcohol PG", smiles: "*C1CCCCO1" },
      { a: "TIPB", full: "1,3,5-triisopropylbenzene", note: "", smiles: "CC(C)c1cc(C(C)C)cc(C(C)C)c1" },
      { a: "TIPS", full: "triisopropylsilyl", note: "Bulky silyl protecting group", smiles: "*[Si](C(C)C)(C(C)C)C(C)C" },
      { a: "TMAO (TMANO)", full: "trimethylamine N-oxide", note: "", smiles: "C[N+](C)(C)[O-]" },
      { a: "TMEDA", full: "N,N,N',N'-tetramethylethylenediamine", note: "Chelating additive for organolithiums", smiles: "CN(C)CCN(C)C" },
      { a: "TMG", full: "1,1,3,3-tetramethylguanidine", note: "", smiles: "CN(C)C(=N)N(C)C" },
      { a: "TMGA", full: "tetramethylguanidinium azide", note: "", smiles: "" },
      { a: "Tmob", full: "2,4,6-trimethoxybenzyl", note: "", smiles: "" },
      { a: "TMP", full: "2,2,6,6-tetramethylpiperidine", note: "", smiles: "CC1(C)CCCC(C)(C)N1" },
      { a: "TMS", full: "trimethylsilyl", note: "Labile silyl protecting group", smiles: "*[Si](C)(C)C" },
      { a: "TMSA", full: "trimethylsilyl azide", note: "", smiles: "C[Si](C)(C)N=[N+]=[N-]" },
      { a: "TMSEE", full: "(trimethylsilyl)ethynyl ether", note: "", smiles: "" },
      { a: "TMU", full: "tetramethylurea", note: "", smiles: "O=C(N(C)C)N(C)C" },
      { a: "TNM", full: "tetranitromethane", note: "", smiles: "O=[N+]([O-])C([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]" },
      { a: "Tol", full: "p-tolyl", note: "", smiles: "*c1ccc(C)cc1" },
      { a: "tolbinap", full: "2,2'-bis(di-p-tolylphosphino)-1,1'-binaphthyl", note: "", smiles: "" },
      { a: "TPAP", full: "tetra-n-propylammonium perruthenate", note: "Catalytic oxidation (with NMO)", smiles: "" },
      { a: "TPP", full: "triphenylphosphine", note: "", smiles: "c1ccc(P(c2ccccc2)c2ccccc2)cc1" },
      { a: "TPP", full: "5,10,15,20-tetraphenylporphyrin", note: "", smiles: "c1ccc(P(c2ccccc2)c2ccccc2)cc1" },
      { a: "TPS", full: "triphenylsilyl", note: "", smiles: "*[Si](c1ccccc1)(c1ccccc1)c1ccccc1" },
      { a: "Tr", full: "trityl (triphenylmethyl)", note: "", smiles: "*C(c1ccccc1)(c1ccccc1)c1ccccc1" },
      { a: "Trisyl", full: "2,4,6-triisopropylbenzenesulfonyl", note: "", smiles: "" },
      { a: "Troc", full: "2,2,2-trichloroethoxycarbonyl", note: "", smiles: "*C(=O)OCC(Cl)(Cl)Cl" },
      { a: "TS", full: "transition state (or transition structure)", note: "Sulfonyl; leaving group / N-PG", smiles: "" },
      { a: "Ts (Tos)", full: "p-toluenesulfonyl", note: "Sulfonyl; leaving group / N-PG", smiles: "*S(=O)(=O)c1ccc(C)cc1" },
      { a: "TSE (TMSE)", full: "2-(trimethylsilyl)ethyl", note: "", smiles: "*CC[Si](C)(C)C" },
      { a: "TTBP", full: "2,4,5-tri-tert-butylpyrimidine", note: "", smiles: "" },
      { a: "TTMSS", full: "tris(trimethylsilyl)silane", note: "", smiles: "[SiH]([Si](C)(C)C)([Si](C)(C)C)[Si](C)(C)C" },
      { a: "TTN", full: "thallium(III)-trinitrate", note: "", smiles: "" },
    ] },
    { group: "U", items: [
      { a: "UHP", full: "urea-hydrogen peroxide complex", note: "", smiles: "NC(N)=O.OO" },
    ] },
    { group: "V", items: [
      { a: "Vitride (Red-Al)", full: "sodium bis(2-methoxyethoxy)aluminum hydride", note: "Soluble hydride reductant", smiles: "[Na][AlH2](OCCOC)OCCOC" },
    ] },
    { group: "W", items: [
      { a: "wk", full: "weeks (length of reaction time)", note: "", smiles: "" },
    ] },
    { group: "Z", items: [
      { a: "Z (Cbz)", full: "benzyloxycarbonyl", note: "Amine PG, removed by hydrogenolysis", smiles: "" },
    ] },
  ];
})();
