// Functional-group transformation index for the Explore ▸ "By Functional Group" lens.
// Each reaction id maps to { from: [...substrate FG families], to: [...product FG families] }
// using the controlled vocabulary in NR_FG.groups. Derived from each reaction's summary.
(function () {
  // Canonical functional-group families, in display order.
  var groups = [
    "Alkane", "Alkene", "Alkyne", "Arene",
    "Alkyl halide", "Aryl halide",
    "Alcohol", "Diol", "Ether", "Epoxide",
    "Aldehyde", "Ketone", "Enone", "Diketone",
    "Carboxylic acid", "Ester", "β-Keto ester", "Amide", "Acyl halide",
    "Amine", "Enamine / iminium", "Nitro", "Nitrile", "Azide", "Diazonium",
    "Oxime / hydrazone",
    "Organometallic", "Boronic acid", "Silane", "Organosulfur",
    "Enol ether", "Organophosphorus",
    "Heterocycle", "Carbocycle"
  ];

  var map = {
    aldol:            { from: ["Aldehyde", "Ketone"], to: ["Alcohol", "Enone"] },
    appel:            { from: ["Alcohol"], to: ["Alkyl halide"] },
    "arndt-eistert":  { from: ["Carboxylic acid"], to: ["Carboxylic acid"] },
    "baeyer-villiger":{ from: ["Ketone"], to: ["Ester"] },
    "baylis-hillman": { from: ["Aldehyde", "Enone"], to: ["Alcohol"] },
    beckmann:         { from: ["Oxime / hydrazone"], to: ["Amide"] },
    birch:            { from: ["Arene"], to: ["Alkene"] },
    "buchwald-hartwig":{ from: ["Aryl halide", "Amine"], to: ["Amine"] },
    cannizzaro:       { from: ["Aldehyde"], to: ["Alcohol", "Carboxylic acid"] },
    "chan-lam":       { from: ["Boronic acid", "Amine"], to: ["Amine", "Ether"] },
    "claisen-cond":   { from: ["Ester"], to: ["β-Keto ester"] },
    "claisen-rearr":  { from: ["Ether"], to: ["Aldehyde", "Ketone"] },
    "corey-fuchs":    { from: ["Aldehyde"], to: ["Alkyne"] },
    curtius:          { from: ["Carboxylic acid", "Azide"], to: ["Amine"] },
    "dess-martin":    { from: ["Alcohol"], to: ["Aldehyde", "Ketone"] },
    "diels-alder":    { from: ["Alkene"], to: ["Carbocycle"] },
    dieckmann:        { from: ["Ester"], to: ["β-Keto ester", "Carbocycle"] },
    "eschweiler-clarke":{ from: ["Amine"], to: ["Amine"] },
    finkelstein:      { from: ["Alkyl halide"], to: ["Alkyl halide"] },
    "fischer-ester":  { from: ["Carboxylic acid", "Alcohol"], to: ["Ester"] },
    "fischer-indole": { from: ["Ketone"], to: ["Heterocycle"] },
    "friedel-crafts-acyl": { from: ["Arene", "Acyl halide"], to: ["Ketone"] },
    "friedel-crafts-alkyl":{ from: ["Arene", "Alkyl halide"], to: ["Arene"] },
    gabriel:          { from: ["Alkyl halide"], to: ["Amine"] },
    grignard:         { from: ["Organometallic", "Aldehyde", "Ketone"], to: ["Alcohol"] },
    grubbs:           { from: ["Alkene"], to: ["Alkene"] },
    heck:             { from: ["Aryl halide", "Alkene"], to: ["Alkene"] },
    "hofmann-elim":   { from: ["Amine"], to: ["Alkene"] },
    "hofmann-rearr":  { from: ["Amide"], to: ["Amine"] },
    hwe:              { from: ["Organophosphorus", "Aldehyde"], to: ["Alkene"] },
    hunsdiecker:      { from: ["Carboxylic acid"], to: ["Alkyl halide"] },
    jones:            { from: ["Alcohol"], to: ["Carboxylic acid", "Ketone"] },
    "kolbe-schmitt":  { from: ["Arene"], to: ["Carboxylic acid"] },
    knoevenagel:      { from: ["Aldehyde"], to: ["Alkene", "Enone"] },
    mannich:          { from: ["Amine", "Ketone"], to: ["Amine", "Ketone"] },
    mcmurry:          { from: ["Ketone"], to: ["Alkene"] },
    michael:          { from: ["Enone"], to: ["Ketone"] },
    mitsunobu:        { from: ["Alcohol"], to: ["Ester", "Ether", "Amine"] },
    mukaiyama:        { from: ["Enol ether", "Aldehyde"], to: ["Alcohol", "Ketone"] },
    negishi:          { from: ["Organometallic", "Aryl halide"], to: ["Arene"] },
    "nozaki-hiyama":  { from: ["Alkyl halide", "Aldehyde"], to: ["Alcohol"] },
    ozonolysis:       { from: ["Alkene"], to: ["Aldehyde", "Ketone"] },
    "paal-knorr":     { from: ["Diketone"], to: ["Heterocycle"] },
    passerini:        { from: ["Carboxylic acid", "Aldehyde"], to: ["Amide"] },
    pinacol:          { from: ["Diol"], to: ["Ketone"] },
    prins:            { from: ["Alkene", "Aldehyde"], to: ["Diol"] },
    reformatsky:      { from: ["Aldehyde", "Ketone", "Ester"], to: ["Alcohol", "Ester"] },
    ritter:           { from: ["Alkene", "Alcohol", "Nitrile"], to: ["Amide"] },
    robinson:         { from: ["Ketone", "Enone"], to: ["Enone", "Carbocycle"] },
    sandmeyer:        { from: ["Diazonium"], to: ["Aryl halide", "Nitrile"] },
    sonogashira:      { from: ["Aryl halide", "Alkyne"], to: ["Alkyne"] },
    staudinger:       { from: ["Azide"], to: ["Amine"] },
    stille:           { from: ["Organometallic", "Aryl halide"], to: ["Arene"] },
    strecker:         { from: ["Aldehyde"], to: ["Amine", "Carboxylic acid"] },
    suzuki:           { from: ["Boronic acid", "Aryl halide"], to: ["Arene"] },
    swern:            { from: ["Alcohol"], to: ["Aldehyde", "Ketone"] },
    ugi:              { from: ["Amine", "Carboxylic acid", "Aldehyde"], to: ["Amide"] },
    wacker:           { from: ["Alkene"], to: ["Ketone"] },
    williamson:       { from: ["Alcohol", "Alkyl halide"], to: ["Ether"] },
    wittig:           { from: ["Organophosphorus", "Aldehyde", "Ketone"], to: ["Alkene"] },
    "wohl-ziegler":   { from: ["Alkene", "Arene"], to: ["Alkyl halide"] },
    "wolff-kishner":  { from: ["Aldehyde", "Ketone"], to: ["Alkane"] },
    acyloin:          { from: ["Ester"], to: ["Ketone", "Alcohol"] },
    "alkyne-zipper":  { from: ["Alkyne"], to: ["Alkyne"] },
    arbuzov:          { from: ["Alkyl halide"], to: ["Organophosphorus"] },
    eas:              { from: ["Arene"], to: ["Arene"] },
    snar:             { from: ["Aryl halide"], to: ["Arene"] },
    "srn1-ar":        { from: ["Aryl halide"], to: ["Arene"] },
    "bamford-stevens":{ from: ["Oxime / hydrazone"], to: ["Alkene"] },
    "barton-decarbox":{ from: ["Carboxylic acid"], to: ["Alkane", "Alkyl halide"] },
    "barton-mccombie":{ from: ["Alcohol"], to: ["Alkane"] },
    benzilic:         { from: ["Diketone"], to: ["Carboxylic acid", "Alcohol"] },
    benzoin:          { from: ["Aldehyde"], to: ["Ketone", "Alcohol"] },
    benzyne:          { from: ["Aryl halide"], to: ["Arene"] },
    bergman:          { from: ["Alkyne"], to: ["Arene"] },
    "bischler-napieralski":{ from: ["Amide"], to: ["Heterocycle"] },
    brook:            { from: ["Silane", "Alcohol"], to: ["Silane", "Ether"] },
    hydroboration:    { from: ["Alkene"], to: ["Alcohol"] },
    buchner:          { from: ["Arene"], to: ["Carbocycle"] },
    chichibabin:      { from: ["Heterocycle"], to: ["Amine", "Heterocycle"] },
    chugaev:          { from: ["Alcohol"], to: ["Alkene"] },
    clemmensen:       { from: ["Aldehyde", "Ketone"], to: ["Alkane"] },
    "cope-elim":      { from: ["Amine"], to: ["Alkene"] },
    "cope-rearr":     { from: ["Alkene"], to: ["Alkene"] },
    cbs:              { from: ["Ketone"], to: ["Alcohol"] },
    "corey-kim":      { from: ["Alcohol"], to: ["Aldehyde", "Ketone"] },
    "corey-winter":   { from: ["Diol"], to: ["Alkene"] },
    criegee:          { from: ["Diol"], to: ["Aldehyde", "Ketone"] },
    cuaac:            { from: ["Azide", "Alkyne"], to: ["Heterocycle"] },
    danheiser:        { from: ["Enone"], to: ["Arene"] },
    darzens:          { from: ["Aldehyde", "Ketone", "Ester"], to: ["Epoxide", "Ester"] },
    "de-mayo":        { from: ["Ketone", "Alkene"], to: ["Diketone"] },
    diazotization:    { from: ["Amine"], to: ["Diazonium"] },
    "dipi-methane":   { from: ["Alkene"], to: ["Carbocycle"] },
    eglinton:         { from: ["Alkyne"], to: ["Alkyne"] },
    "electro-addn":   { from: ["Alkene"], to: ["Alkyl halide", "Alcohol"] },
    "elim-mech":      { from: ["Alkyl halide"], to: ["Alkene"] },
    ene:              { from: ["Alkene"], to: ["Alkene"] },
    "eschenmoser-methen":{ from: ["Ketone"], to: ["Enone"] },
    "eschenmoser-tanabe":{ from: ["Epoxide", "Ketone"], to: ["Alkyne", "Aldehyde"] },
    "evans-tishchenko":{ from: ["Ketone", "Alcohol"], to: ["Ester", "Diol"] },
    favorskii:        { from: ["Alkyl halide", "Ketone"], to: ["Ester"] },
    "fleming-tamao":  { from: ["Silane"], to: ["Alcohol"] },
    gewald:           { from: ["Ketone", "Nitrile"], to: ["Heterocycle", "Amine"] },
    glaser:           { from: ["Alkyne"], to: ["Alkyne"] },
    grob:             { from: ["Alkyl halide"], to: ["Alkene", "Ketone"] },
    haloform:         { from: ["Ketone"], to: ["Carboxylic acid", "Alkyl halide"] },
    hvz:              { from: ["Carboxylic acid"], to: ["Carboxylic acid", "Alkyl halide"] },
    henry:            { from: ["Nitro", "Aldehyde", "Ketone"], to: ["Alcohol", "Nitro"] },
    hiyama:           { from: ["Silane", "Aryl halide"], to: ["Arene"] },
    "ireland-claisen":{ from: ["Ester"], to: ["Carboxylic acid"] },
    jacobsen:         { from: ["Alkene"], to: ["Epoxide"] },
    "johnson-claisen":{ from: ["Alcohol"], to: ["Ester"] },
    "julia-lythgoe":  { from: ["Organosulfur", "Aldehyde"], to: ["Alkene"] },
    "julia-kocienski":{ from: ["Organosulfur", "Aldehyde"], to: ["Alkene"] },
    "kornblum-delamare":{ from: ["Ether"], to: ["Ketone", "Alcohol"] },
    krapcho:          { from: ["Ester", "β-Keto ester"], to: ["Ester"] },
    kucherov:         { from: ["Alkyne"], to: ["Ketone"] },
    kumada:           { from: ["Organometallic", "Aryl halide"], to: ["Arene"] },
    "ley-griffith":   { from: ["Alcohol"], to: ["Aldehyde", "Ketone"] },
    "liebeskind-srogl":{ from: ["Ester", "Boronic acid"], to: ["Ketone"] },
    luche:            { from: ["Enone"], to: ["Alcohol"] },
    mpv:              { from: ["Ketone"], to: ["Alcohol"] },
    minisci:          { from: ["Heterocycle"], to: ["Heterocycle"] },
    "mislow-evans":   { from: ["Organosulfur"], to: ["Alcohol"] },
    miyaura:          { from: ["Aryl halide"], to: ["Boronic acid"] },
    "mizoroki-heck":  { from: ["Alkene", "Aryl halide"], to: ["Alkene"] },
    "mukaiyama-hydration":{ from: ["Alkene"], to: ["Alcohol"] },
    nazarov:          { from: ["Enone"], to: ["Enone", "Carbocycle"] },
    nef:              { from: ["Nitro"], to: ["Aldehyde", "Ketone"] },
    nicholas:         { from: ["Alkyne", "Alcohol"], to: ["Alkyne", "Ether"] },
    norrish:          { from: ["Ketone"], to: ["Aldehyde", "Alkene"] },
    "sn-mech":        { from: ["Alkyl halide"], to: ["Alcohol", "Ether", "Amine"] },
    oppenauer:        { from: ["Alcohol"], to: ["Ketone"] },
    overman:          { from: ["Alcohol"], to: ["Amide", "Amine"] },
    "oxy-cope":       { from: ["Alcohol", "Alkene"], to: ["Aldehyde", "Ketone"] },
    "paterno-buchi":  { from: ["Aldehyde", "Ketone", "Alkene"], to: ["Ether"] },
    "pauson-khand":   { from: ["Alkyne", "Alkene"], to: ["Enone", "Carbocycle"] },
    payne:            { from: ["Epoxide", "Alcohol"], to: ["Epoxide", "Alcohol"] },
    "peptide-coupling":{ from: ["Carboxylic acid", "Amine"], to: ["Amide"] },
    peterson:         { from: ["Silane", "Aldehyde", "Ketone"], to: ["Alkene"] },
    "pfitzner-moffatt":{ from: ["Alcohol"], to: ["Aldehyde", "Ketone"] },
    "pictet-spengler":{ from: ["Amine", "Aldehyde"], to: ["Heterocycle"] },
    polonovski:       { from: ["Amine"], to: ["Enamine / iminium"] },
    prilezhaev:       { from: ["Alkene"], to: ["Epoxide"] },
    pummerer:         { from: ["Organosulfur"], to: ["Organosulfur", "Ester"] },
    "ramberg-backlund":{ from: ["Organosulfur", "Alkyl halide"], to: ["Alkene"] },
    ramirez:          { from: ["Aldehyde"], to: ["Alkene", "Alkyl halide"] },
    riley:            { from: ["Ketone"], to: ["Diketone"] },
    rosenmund:        { from: ["Acyl halide"], to: ["Aldehyde"] },
    rubottom:         { from: ["Enol ether"], to: ["Ketone", "Alcohol"] },
    saegusa:          { from: ["Enol ether"], to: ["Enone"] },
    sakurai:          { from: ["Silane"], to: ["Alkene"] },
    schmidt:          { from: ["Ketone", "Carboxylic acid", "Azide"], to: ["Amine", "Amide"] },
    shapiro:          { from: ["Oxime / hydrazone"], to: ["Alkene", "Organometallic"] },
    "sharpless-dihydrox":{ from: ["Alkene"], to: ["Diol"] },
    "sharpless-epox": { from: ["Alcohol", "Alkene"], to: ["Epoxide"] },
    "simmons-smith":  { from: ["Alkene"], to: ["Carbocycle"] },
    steglich:         { from: ["Carboxylic acid", "Alcohol"], to: ["Ester"] },
    stetter:          { from: ["Aldehyde", "Enone"], to: ["Diketone"] },
    "stork-enamine":  { from: ["Ketone"], to: ["Enamine / iminium", "Ketone"] },
    takai:            { from: ["Aldehyde"], to: ["Alkene", "Alkyl halide"] },
    tebbe:            { from: ["Ketone", "Aldehyde", "Ester"], to: ["Alkene", "Enol ether"] },
    "tsuji-trost":    { from: ["Ester"], to: ["Alkene"] },
    ullmann:          { from: ["Aryl halide"], to: ["Arene", "Amine", "Ether"] },
    upjohn:           { from: ["Alkene"], to: ["Diol"] },
    vilsmeier:        { from: ["Arene"], to: ["Aldehyde"] },
    "wagner-meerwein":{ from: ["Alkene", "Alcohol"], to: ["Alkene"] },
    wharton:          { from: ["Epoxide", "Ketone"], to: ["Alcohol"] },
    wolff:            { from: ["Ketone"], to: ["Carboxylic acid"] },
    "wittig-rearr":   { from: ["Ether"], to: ["Alcohol"] },
    "baylis-hillman-classic": { from: ["Aldehyde", "Enone"], to: ["Alcohol"] },
    semipinacol:      { from: ["Diol", "Epoxide"], to: ["Ketone", "Aldehyde"] }
  };

  window.NR_FG = { groups: groups, map: map };
})();
