// Verified SMILES for abbreviations that are specific molecules / groups.
// Keyed by the EXACT abbreviation string used in nr-abbrev.js.
// '*' marks an attachment point for substituent groups (renders as a stub).
// Pure concepts, techniques, generic placeholders and a few exotic metal
// complexes are intentionally omitted (left text-only for you to fill in).
(function () {
  window.NR_SMILES = {
    // ---- crown ether / misc ----
    "18-Cr-6": "O1CCOCCOCCOCCOCCOCC1",
    // ---- substituent & protecting groups (attachment = *) ----
    "Ac": "*C(C)=O",
    "acac": "CC(=O)CC(C)=O",
    "ad": "*C1(CC2CC3C1)CC(C2)C3",
    "Alloc": "*C(=O)OCC=C",
    "Am": "*CCCCC",
    "An": "*c1ccc(OC)cc1",
    "Bn": "*Cc1ccccc1",
    "Boc": "*C(=O)OC(C)(C)C",
    "BOM": "*COCc1ccccc1",
    "Bz": "*C(=O)c1ccccc1",
    "Bu (nBu)": "*CCCC",
    "CA": "*C(=O)CCl",
    "Cbz (Z)": "*C(=O)OCc1ccccc1",
    "Chx (Cy)": "*C1CCCCC1",
    "Cp": "*C1C=CC=C1",
    "DMT": "*C(c1ccc(OC)cc1)(c1ccc(OC)cc1)c1ccccc1",
    "EE": "*C(C)OCC",
    "EOM": "*COCC",
    "Et": "*CC",
    "Fl": "*C1c2ccccc2-c2ccccc21",
    "Fmoc": "*C(=O)OCC1c2ccccc2-c2ccccc21",
    "Me": "*C",
    "MEM": "*COCCOC",
    "MOM": "*COC",
    "MTM": "*CSC",
    "Ms": "*S(=O)(=O)C",
    "Mes": "*c1c(C)cc(C)cc1C",
    "Naph (Np)": "*c1cccc2ccccc12",
    "Ns": "*S(=O)(=O)c1ccccc1[N+](=O)[O-]",
    "Nos": "*S(=O)(=O)c1ccc(cc1)[N+](=O)[O-]",
    "Bs": "*S(=O)(=O)c1ccc(Br)cc1",
    "Pf": "*C1(c2ccccc2)c2ccccc2-c2ccccc21",
    "Ph": "*c1ccccc1",
    "Phth": "*N1C(=O)c2ccccc2C1=O",
    "Piv": "*C(=O)C(C)(C)C",
    "PMB (MPM)": "*Cc1ccc(OC)cc1",
    "MPM (PMB)": "*Cc1ccc(OC)cc1",
    "PMP": "*c1ccc(OC)cc1",
    "PNB": "*Cc1ccc(cc1)[N+](=O)[O-]",
    "PNZ": "*C(=O)OCc1ccc(cc1)[N+](=O)[O-]",
    "Pr": "*CCC",
    "SEM": "*COCC[Si](C)(C)C",
    "Sia": "*C(C)C(C)C",
    "TBDMS (TBS)": "*[Si](C)(C)C(C)(C)C",
    "TBDPS (BPS)": "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C",
    "BPS (TBDPS)": "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C",
    "DPS (TBDPS or BPS)": "*[Si](c1ccccc1)(c1ccccc1)C(C)(C)C",
    "TDS": "*[Si](C)(C)C(C)C(C)(C)C",
    "TES": "*[Si](CC)(CC)CC",
    "Teoc": "*C(=O)OCC[Si](C)(C)C",
    "Tf": "*S(=O)(=O)C(F)(F)F",
    "thexyl": "*C(C)(C)C(C)C",
    "THP": "*C1CCCCO1",
    "TIPS": "*[Si](C(C)C)(C(C)C)C(C)C",
    "TMS": "*[Si](C)(C)C",
    "Tol": "*c1ccc(C)cc1",
    "TPS": "*[Si](c1ccccc1)(c1ccccc1)c1ccccc1",
    "Tr": "*C(c1ccccc1)(c1ccccc1)c1ccccc1",
    "Troc": "*C(=O)OCC(Cl)(Cl)Cl",
    "Ts (Tos)": "*S(=O)(=O)c1ccc(C)cc1",
    "TSE (TMSE)": "*CC[Si](C)(C)C",
    // ---- reagents & full molecules ----
    "ADDP": "O=C(N1CCCCC1)N=NC(=O)N1CCCCC1",
    "AIBN": "N#CC(C)(C)N=NC(C)(C)C#N",
    "AQN": "O=C1c2ccccc2C(=O)c2ccccc12",
    "BHT": "Cc1cc(C(C)(C)C)c(O)c(C(C)(C)C)c1",
    "BINOL": "Oc1ccc2ccccc2c1-c1c(O)ccc2ccccc12",
    "bipy": "c1ccc(-c2ccccn2)nc1",
    "BMS": "B.CSC",
    "BPD": "CC1(C)OB(OC1(C)C)B1OC(C)(C)C(C)(C)O1",
    "BPO": "O=C(OOC(=O)c1ccccc1)c1ccccc1",
    "BQ": "O=C1C=CC(=O)C=C1",
    "BTMSA": "C[Si](C)(C)C#C[Si](C)(C)C",
    "BTSP": "C[Si](C)(C)OO[Si](C)(C)C",
    "BCME": "ClCOCCl",
    "CB": "O1c2ccccc2OB1",
    "CDI": "O=C(n1ccnc1)n1ccnc1",
    "CHD": "C1CC=CC=C1",
    "COD": "C1CC=CCCC=C1",
    "COT": "C1CC=CC=CC=C1",
    "CSA": "CC1(C)C2CCC1(CS(=O)(=O)O)C(=O)C2",
    "CSI": "O=C=NS(=O)(=O)Cl",
    "DABCO": "C1CN2CCN1CC2",
    "DAST": "CCN(CC)S(F)(F)F",
    "DBA (dba)": "O=C(C=Cc1ccccc1)C=Cc1ccccc1",
    "DBM": "O=C(CC(=O)c1ccccc1)c1ccccc1",
    "DBU": "C1CCC2=NCCCN2CC1",
    "DCA": "N#Cc1c2ccccc2c(C#N)c2ccccc12",
    "DCB": "Clc1ccccc1Cl",
    "DCC": "C1CCCCC1N=C=NC1CCCCC1",
    "DCE": "CC(Cl)Cl",
    "DCM": "ClCCl",
    "DCU": "C1CCCCC1NC(=O)NC1CCCCC1",
    "DDQ": "O=C1C(Cl)=C(Cl)C(=O)C(C#N)=C1C#N",
    "DEAD": "CCOC(=O)N=NC(=O)OCC",
    "DBAD": "CC(C)(C)OC(=O)N=NC(=O)OC(C)(C)C",
    "DTBAD (DBAD)": "CC(C)(C)OC(=O)N=NC(=O)OC(C)(C)C",
    "DET": "CCOC(=O)C(O)C(O)C(=O)OCC",
    "DIAD": "CC(C)OC(=O)N=NC(=O)OC(C)C",
    "DIPT": "CC(C)OC(=O)C(O)C(O)C(=O)OC(C)C",
    "DHP": "O1CCCC=C1",
    "DIBAL (DIBAH, DIBAL-H)": "CC(C)C[AlH]CC(C)C",
    "DIC": "CC(C)N=C=NC(C)C",
    "DIPAMP": "COc1ccccc1P(CCP(c1ccccc1)c1ccccc1OC)c1ccccc1",
    "DIPEA (Hunig's base)": "CCN(C(C)C)C(C)C",
    "DPA (DIPA)": "CC(C)NC(C)C",
    "DMA (DMAC)": "CC(=O)N(C)C",
    "DMAD": "COC(=O)C#CC(=O)OC",
    "DMAP": "CN(C)c1ccncc1",
    "DMB": "COc1cccc(OC)c1",
    "DMDO": "CC1(C)OO1",
    "DME": "COCCOC",
    "DMF": "CN(C)C=O",
    "DMI": "O=C1N(C)CCN1C",
    "DMP": "CC(=O)OI1(OC(C)=O)(OC(C)=O)OC(=O)c2ccccc21",
    "DMPU": "O=C1N(C)CCCN1C",
    "DMS": "CSC",
    "DMSO": "CS(C)=O",
    "DPPA": "O=P(Oc1ccccc1)(Oc1ccccc1)N=[N+]=[N-]",
    "DPDM": "[N-]=[N+]=C(c1ccccc1)c1ccccc1",
    "DPEDA": "NC(c1ccccc1)C(N)c1ccccc1",
    "DPIBF": "c1ccc(-c2c3ccccc3c(-c3ccccc3)o2)cc1",
    "DTBB": "CC(C)(C)c1ccc(-c2ccc(C(C)(C)C)cc2)cc1",
    "DTBP": "CC(C)(C)c1cccc(C(C)(C)C)n1",
    "DTBMP": "Cc1cc(C(C)(C)C)nc(C(C)(C)C)c1",
    "DTE": "SCC(O)C(O)CS",
    "DVS": "C=C[Si](C)(C)O[Si](C)(C)C=C",
    "EDA": "CCOC(=O)C=[N+]=[N-]",
    "EDC (EDAC)": "CCN=C=NCCCN(C)C",
    "EDCI": "CCN=C=NCCCN(C)C",
    "EDTA": "OC(=O)CN(CC(=O)O)CCN(CC(=O)O)CC(=O)O",
    "en": "NCCN",
    "EVE": "C=COCC",
    "hfacac": "O=C(CC(=O)C(F)(F)F)C(F)(F)F",
    "HFIP": "OC(C(F)(F)F)C(F)(F)F",
    "HMDS": "C[Si](C)(C)N[Si](C)(C)C",
    "HMPA": "O=P(N(C)C)(N(C)C)N(C)C",
    "HMPT": "P(N(C)C)(N(C)C)N(C)C",
    "HOAt": "On1nnc2ncccc21",
    "HOBt (HOBT)": "On1nnc2ccccc21",
    "HOSu": "O=C1CCC(=O)N1O",
    "Imid (Im)": "c1c[nH]cn1",
    "IPA": "CC(C)O",
    "L-selectride": "[Li][BH](C(C)CC)(C(C)CC)C(C)CC",
    "LAB": "[Li][BH3]N",
    "LAH": "[Li+].[AlH4-]",
    "LDA": "[Li]N(C(C)C)C(C)C",
    "KHMDS": "[K]N([Si](C)(C)C)[Si](C)(C)C",
    "LHMDS (LiHMDS)": "[Li]N([Si](C)(C)C)[Si](C)(C)C",
    "NaHMDS": "[Na]N([Si](C)(C)C)[Si](C)(C)C",
    "LiTMP (LTMP)": "[Li]N1C(C)(C)CCCC1(C)C",
    "lut": "Cc1cccc(C)n1",
    "MA": "O=C1OC(=O)C=C1",
    "m-CPBA": "O=C(OO)c1cccc(Cl)c1",
    "MIC": "CN=C=O",
    "MSA": "CS(=O)(=O)O",
    "MSH": "Cc1cc(C)c(S(=O)(=O)ON)c(C)c1",
    "MTEE (MTBE)": "COC(C)(C)C",
    "MVK": "C=CC(C)=O",
    "NBA": "CC(=O)NBr",
    "NBS": "O=C1CCC(=O)N1Br",
    "NCS": "O=C1CCC(=O)N1Cl",
    "NIS": "O=C1CCC(=O)N1I",
    "NHPI": "O=C1c2ccccc2C(=O)N1O",
    "NMM": "CN1CCOCC1",
    "NMO": "C[N+]1([O-])CCOCC1",
    "NMP": "O=C1CCCN1C",
    "MPD (NMP)": "O=C1CCCN1C",
    "NPM": "O=C1C=CC(=O)N1c1ccccc1",
    "PMP ": "CN1C(C)(C)CCCC1(C)C",
    "phen": "c1ccc2ccc3cccnc3c2n1",
    "PHAL": "c1ccc2cnncc2c1",
    "PTSA (or TsOH)": "Cc1ccc(S(=O)(=O)O)cc1",
    "Py (pyr)": "c1ccncc1",
    "RaNi": "[Ni]",
    "Red-Al": "[Na][AlH2](OCCOC)OCCOC",
    "Vitride (Red-Al)": "[Na][AlH2](OCCOC)OCCOC",
    "Salen": "Oc1ccccc1C=NCCN=Cc1ccccc1O",
    "TBAB": "CCCC[N+](CCCC)(CCCC)CCCC.[Br-]",
    "TBAF": "CCCC[N+](CCCC)(CCCC)CCCC.[F-]",
    "TBAI": "CCCC[N+](CCCC)(CCCC)CCCC.[I-]",
    "TBH": "CC(C)(C)OCl",
    "TBHP": "CC(C)(C)OO",
    "TBP": "CCCCP(CCCC)CCCC",
    "TBTH": "CCCC[SnH](CCCC)CCCC",
    "TCCA": "O=C1N(Cl)C(=O)N(Cl)C(=O)N1Cl",
    "TCDI": "S=C(n1ccnc1)n1ccnc1",
    "TCNE": "N#CC(C#N)=C(C#N)C#N",
    "TEA": "CCN(CC)CC",
    "TEMPO": "CC1(C)CCCC(C)(C)N1[O]",
    "TEP": "CCOP(OCC)OCC",
    "TFA": "OC(=O)C(F)(F)F",
    "Tfa": "NC(=O)C(F)(F)F",
    "TFAA": "O=C(OC(=O)C(F)(F)F)C(F)(F)F",
    "TFE": "OCC(F)(F)F",
    "TFMSA": "OS(=O)(=O)C(F)(F)F",
    "TFP": "c1ccc(o1)P(c1ccco1)c1ccco1",
    "TMEDA": "CN(C)CCN(C)C",
    "TMG": "CN(C)C(=N)N(C)C",
    "TMP": "CC1(C)CCCC(C)(C)N1",
    "TMSA": "C[Si](C)(C)N=[N+]=[N-]",
    "TMU": "O=C(N(C)C)N(C)C",
    "TNM": "O=[N+]([O-])C([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]",
    "TPP": "c1ccc(P(c2ccccc2)c2ccccc2)cc1",
    "TTMSS": "[SiH]([Si](C)(C)C)([Si](C)(C)C)[Si](C)(C)C",
    "THF": "C1CCOC1",
    "TIPB": "CC(C)c1cc(C(C)C)cc(C(C)C)c1",
    "dppe": "c1ccc(P(CCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1",
    "dppm": "c1ccc(P(CP(c2ccccc2)c2ccccc2)c2ccccc2)cc1",
    "dppp": "c1ccc(P(CCCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1",
    "Dppb (ddpb)": "c1ccc(P(CCCCP(c2ccccc2)c2ccccc2)c2ccccc2)cc1",
    "CHIRAPHOS": "CC(P(c1ccccc1)c1ccccc1)C(C)P(c1ccccc1)c1ccccc1",
    "DPBP": "c1ccc(P(c2ccccc2)c2ccccc2-c2ccccc2P(c2ccccc2)c2ccccc2)cc1",
    "DHP ": "O1CCCC=C1",
    "MMPP (MMPT)": "",
    "TMAO (TMANO)": "C[N+](C)(C)[O-]",
    "DMTSF": "C[S+](C)SC.[B-](F)(F)(F)F",
    "MTAD": "O=C1N(C)C(=O)N=N1",
    "UHP": "NC(N)=O.OO",
    "TCNQ": "N#CC(C#N)=C1C=CC(=C(C#N)C#N)C=C1"
  };
})();
